package parser;
/* Generated By:JavaCC: Do not edit this line. SyntaxCheckerConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface SyntaxCheckerConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int CRLF = 20;
  /** RegularExpression Id. */
  int NUM = 21;
  /** RegularExpression Id. */
  int QUOTED = 22;
  /** RegularExpression Id. */
  int WORD = 23;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"BEGIN\"",
    "\":\"",
    "\"VCARD\"",
    "\"VERSION\"",
    "\"2.1\"",
    "\"END\"",
    "\"N\"",
    "\"FN\"",
    "\"ADR\"",
    "\"BDAY\"",
    "\"TEL\"",
    "\"CHARSET=UTF-8\"",
    "\"TYPE=\"",
    "\"EMAIL\"",
    "\"PHOTO\"",
    "\"ENCODING=BASE64\"",
    "\"ENCODING=QUOTED-PRINTABLE\"",
    "\";\"",
    "\"\\r\\n\"",
    "<NUM>",
    "<QUOTED>",
    "<WORD>",
  };

}
